apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-az2y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-az2y
    app.kubernetes.io/part-of: tkrw-pr714-0075-0065-app
  name: devfile-sample-az2y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-az2y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-az2y
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0065-tenant/tkrw-pr714-0075-0065-app/devfile-sample-az2y@sha256:cf813e1a76e74b59a27a56593a1ed96479dbe624f7a52f32bd3a7643a8d8d0f9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
